name: ipyniivue-dev
channels:
    - conda-forge
dependencies:
    - nodejs
    - pip
    - yarn
    - pip:
        - traitlets
        - ipywidgets>=7.4
        - setuptools
        - jupyter
        - jupyterlab>=0.34
        - notebook>=5.3
        - jupyter_ui_poll
